root = "." # The root directory of the project
tmp_dir = "tmp" # The temporary directory where air will store its temporary files

[build] # The build configuration
bin = "bin/api-gateway" # The name of the binary file to be generated after building the project
cmd = "go build -o bin/api-gateway cmd/api-gateway/main.go" # The command to build the project
exclude_dir = ["tmp", "client"]  # Specifies the directories to be excluded from monitoring for changes
include_ext = ["go"]
exclude_regex = ["_test\\.go"]