services:
  postgres:
    image: postgres:16-alpine
    container_name: penfeel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: penfeel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.base
    container_name: penfeel-migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: penfeel
      DB_SSLMODE: disable
      MIGRATION_ENABLED: "true"
      MIGRATION_PATH: "/app/migrations"
    volumes:
      - ./:/app
    command: ["./scripts/run_migrations.sh"]
    profiles:
      - manual

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: penfeel-auth
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: penfeel
      DB_SSLMODE: disable
      GRPC_PORT: 9090
      JWT_SECRET: "your-auth-secret-key-change-in-production"
      JWT_REFRESH_SECRET: "your-refresh-secret-key-change-in-production"
      MIGRATION_ENABLED: "true"
      MIGRATION_PATH: "/app/migrations"
    ports:
      - "9090:9090"
    volumes:
    - ./:/app
    command: ["air", "-c", "auth.air.toml"]  

  document-service:
    build:
      context: .
      dockerfile: Dockerfile.document
    container_name: penfeel-document
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: penfeel
      DB_SSLMODE: disable
      GRPC_PORT: 9091
      MIGRATION_ENABLED: "true"
      MIGRATION_PATH: "/app/migrations"
    ports:
      - "9091:9091"
    volumes:
    - ./:/app
    command: ["air", "-c", "document.air.toml"]  

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: penfeel-api
    depends_on:
      - auth-service
      - document-service
    environment:
      SERVER_PORT: 8080
      SERVER_GRPC_PORT: 9090
      AUTH_SERVICE_HOST: auth-service
      DOCUMENT_SERVICE_HOST: document-service
      DOCUMENT_SERVICE_PORT: 9091
      ENV: dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: ["air", "-c", "api.air.toml"]      
volumes:
  postgres_data: 